apiVersion: v1
kind: Service
metadata:
  name: stock-bot-v3-jupyter-service
  namespace: stock-bot-v3
  labels:
    app: stock-bot-v3-jupyter
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8888
    protocol: TCP
    name: jupyter
  selector:
    app: stock-bot-v3-jupyter
