apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stock-bot-v3-jupyter-pvc
  namespace: stock-bot-v3
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp2
