apiVersion: v1
kind: Secret
metadata:
  name: aws-secrets
  namespace: stock-bot-v3
type: Opaque
data:
  # Base64 encoded values
  aws-access-key-id: QUtJQVVKUlRLUU5VTFdGV1JNTlY
  aws-secret-access-key: QWlWYTJOLzVsL0V4VE5kaUM3UG5XL242ZDNwQy9rOXlINEdTazBiVg
  s3-bucket-name: c3RvY2stYW5hbHlzaXMtYm90
