apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stock-bot-pvc
  namespace: stock-bot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp2
